/* Site content. Everything Andra will later edit in the CMS lives here.
   Image values are asset keys (see assets/manifest.json); build.py inlines them. */

const PROJECTS = [
  { slug:'palau', name:'Four Seasons Explorer', client:'Four Seasons', location:'Palau', year:'2026',
    services:['Photography','Film','Drone','Lifestyle Production'], logo:'four-seasons.svg',
    hero:'film-palau-1', heroM:'w-palau', coverV:'w-palau', coverL:'film-palau-1',
    blocks:[
      {t:'large', k:'palau-1'},
      {t:'pair', k:['palau-2','palau-3']},
      {t:'full', k:'palau-4'},
      {t:'mixed', k:['palau-5','film-palau-2'], video:1},
      {t:'pair', k:['palau-6','palau-7']},
      {t:'video', k:'film-palau-3'},
      {t:'pair', k:['palau-8','palau-9']},
      {t:'large', k:'palau-10', side:'right'} ]},
  { slug:'heritance', name:'Heritance Aarah', client:'Heritance Hotels & Resorts', location:'Raa Atoll, Maldives', year:'2026',
    services:['Photography','Film','Drone'], logo:'heritance-aarah.svg',
    hero:'film-heritance-1', heroM:'hv-heritance', coverV:'hv-heritance', coverL:'w-heritance',
    blocks:[
      {t:'drone', k:'heritance-1'},
      {t:'pair', k:['heritance-2','heritance-3']},
      {t:'video', k:'film-heritance-2'},
      {t:'large', k:'heritance-4'},
      {t:'pair', k:['heritance-5','heritance-6']},
      {t:'mixed', k:['heritance-7','film-heritance-3'], video:1},
      {t:'pair', k:['heritance-8','heritance-9']},
      {t:'large', k:'heritance-10', side:'right'} ]},
  { slug:'sixsenses', name:'Six Senses Kocataş Mansions', client:'Six Senses', location:'Istanbul, Türkiye', year:'',
    services:['Photography','Film'], logo:'six-senses.png',
    hero:'pl-sixsenses', heroM:'w-sixsenses', coverV:'w-sixsenses', coverL:'pl-sixsenses',
    blocks:[
      {t:'large', k:'sixsenses-1'},
      {t:'pair', k:['sixsenses-2','sixsenses-3']},
      {t:'video', k:'pl-sixsenses-2'},
      {t:'pair', k:['sixsenses-4','sixsenses-5']},
      {t:'large', k:'sixsenses-6', side:'right'},
      {t:'pair', k:['sixsenses-7','sixsenses-8']},
      {t:'pair', k:['sixsenses-9','sixsenses-10']} ]},
  { slug:'hoiana', name:'Hoiana Resort & Golf', client:'Hoiana Resort & Golf', location:'Hội An, Vietnam', year:'',
    services:['Photography','Film'], logo:'hoiana.png',
    hero:'pl-hoiana', heroM:'hv-hoiana', coverV:'hv-hoiana', coverL:'w-hoiana',
    blocks:[
      {t:'large', k:'hoiana-1'},
      {t:'pair', k:['hoiana-2','hoiana-3']},
      {t:'video', k:'pl-hoiana-2'},
      {t:'pair', k:['hoiana-4','hoiana-5']},
      {t:'large', k:'hoiana-6', side:'right'},
      {t:'pair', k:['hoiana-7','hoiana-8']},
      {t:'pair', k:['hoiana-9','hoiana-10']} ]},
  { slug:'bangkok', name:'Four Seasons Bangkok', client:'Four Seasons', location:'Bangkok, Thailand', year:'',
    services:['Photography','Film'], logo:'four-seasons.svg',
    hero:'film-bangkok-2', heroM:'w-bangkok', coverV:'w-bangkok', coverL:'film-bangkok-2',
    blocks:[
      {t:'large', k:'bangkok-1'},
      {t:'pair', k:['bangkok-2','bangkok-3']},
      {t:'video', k:'film-bangkok-1'},
      {t:'pair', k:['bangkok-4','bangkok-5']},
      {t:'large', k:'bangkok-6', side:'right'},
      {t:'pair', k:['bangkok-7','bangkok-8']},
      {t:'pair', k:['bangkok-9','bangkok-10']} ]},
  { slug:'hideaway', name:'Hideaway Beach Resort & Spa', client:'Hideaway Beach Resort & Spa', location:'Haa Alifu Atoll, Maldives', year:'2026',
    services:['Photography','Film','Drone'], logo:null,
    hero:'w-hideaway', heroM:'hv-hideaway', coverV:'hv-hideaway', coverL:'w-hideaway',
    blocks:[
      {t:'large', k:'hideaway-1'},
      {t:'pair', k:['hideaway-2','hideaway-3']},
      {t:'drone', k:'hideaway-9'},
      {t:'pair', k:['hideaway-4','hideaway-5']},
      {t:'large', k:'hideaway-6', side:'right'},
      {t:'pair', k:['hideaway-7','hideaway-8']},
      {t:'large', k:'hideaway-10'} ]},
  { slug:'millennium', name:'Millennium Hotels', client:'Millennium Hotels and Resorts', location:'Singapore', year:'',
    services:['Photography','Film'], logo:'millenium.png',
    hero:'pl-millennium', heroM:'hv-millennium', coverV:'hv-millennium', coverL:'pl-millennium',
    blocks:[
      {t:'large', k:'millennium-1'},
      {t:'pair', k:['millennium-2','millennium-3']},
      {t:'video', k:'pl-millennium-2'},
      {t:'pair', k:['millennium-4','millennium-5']},
      {t:'large', k:'millennium-6', side:'right'},
      {t:'pair', k:['millennium-7','millennium-8']},
      {t:'pair', k:['millennium-9','millennium-10']} ]},
  { slug:'westin', name:'Westin', client:'The Westin', location:'', year:'',
    services:['Photography','Film','Drone'], logo:'westin.svg',
    hero:'film-westin-3', heroM:'westin-2', coverV:'westin-2', coverL:'film-westin-1',
    blocks:[
      {t:'drone', k:'film-westin-1'},
      {t:'pair', k:['westin-1','westin-2']},
      {t:'large', k:'westin-3'},
      {t:'pair', k:['westin-4','westin-6']},
      {t:'video', k:'film-westin-2'},
      {t:'pair', k:['westin-7','westin-8']},
      {t:'pair', k:['westin-9','westin-10']} ]},
  { slug:'intercontinental', name:'InterContinental', client:'InterContinental Hotels & Resorts', location:'', year:'',
    services:['Film'], logo:'intercontinental.png',
    hero:'film-intercontinental-2', heroM:'hv-intercontinental', coverV:'hv-intercontinental', coverL:'film-intercontinental-1',
    blocks:[
      {t:'large', k:'hv-intercontinental'},
      {t:'video', k:'film-intercontinental-1'},
      {t:'video', k:'film-intercontinental-3'} ]},
];

/* Photography: one list, multi-category, manually ordered. */
const CATS = [
  ['hospitality','Hospitality'],['lifestyle','Lifestyle'],['food-beverage','Food & Beverage'],
  ['nature','Nature'],['interiors','Interiors'],['drone','Drone'],['product','Product']];
const P = (k,cats,project,loc) => ({k,cats,project,loc});
const PHOTOS = [
  P('palau-1',['drone','nature'],'palau','Palau'),
  P('p-1',['hospitality'],null,''),
  P('ph-food-3',['food-beverage'],null,''),
  P('heritance-2',['lifestyle','nature'],'heritance','Raa Atoll, Maldives'),
  P('ph-interiors-4',['interiors'],null,''),
  P('sixsenses-2',['interiors','hospitality'],'sixsenses','Istanbul, Türkiye'),
  P('heritance-1',['drone'],'heritance','Raa Atoll, Maldives'),
  P('ph-hospitality-1',['hospitality'],null,''),
  P('hoiana-4',['interiors','hospitality'],'hoiana','Hội An, Vietnam'),
  P('ph-food-6',['food-beverage'],null,''),
  P('palau-4',['nature'],'palau','Palau'),
  P('ph-lifestyle-1',['lifestyle'],null,''),
  P('ph-product-2',['product'],null,''),
  P('hideaway-4',['lifestyle','hospitality'],'hideaway','Haa Alifu Atoll, Maldives'),
  P('p-3',['drone','hospitality'],null,''),
  P('ph-interiors-7',['interiors'],null,''),
  P('millennium-1',['lifestyle'],'millennium','Singapore'),
  P('ph-food-8',['food-beverage'],null,''),
  P('heritance-10',['nature','drone'],'heritance','Raa Atoll, Maldives'),
  P('ph-hospitality-3',['hospitality','interiors'],null,''),
  P('bangkok-2',['lifestyle'],'bangkok','Bangkok, Thailand'),
  P('ph-product-3',['product'],null,''),
  P('westin-1',['drone','hospitality'],'westin',''),
  P('ph-lifestyle-6',['lifestyle','hospitality'],null,''),
  P('hoiana-10',['food-beverage'],'hoiana','Hội An, Vietnam'),
  P('ph-nature-7',['nature'],null,''),
  P('sixsenses-6',['nature','lifestyle'],'sixsenses','Istanbul, Türkiye'),
  P('ph-interiors-5',['interiors'],null,''),
  P('hideaway-9',['drone','nature'],'hideaway','Haa Alifu Atoll, Maldives'),
  P('ph-food-5',['food-beverage'],null,''),
  P('palau-6',['interiors','lifestyle'],'palau','Palau'),
  P('ph-product-6',['product'],null,''),
  P('ph-hospitality-5',['hospitality'],null,''),
  P('ph-lifestyle-8',['lifestyle'],null,''),
  P('millennium-8',['food-beverage'],'millennium','Singapore'),
  P('ph-nature-2',['nature'],null,''),
  P('westin-8',['drone','nature'],'westin',''),
  P('ph-interiors-1',['interiors'],null,''),
  P('ph-food-1',['food-beverage'],null,''),
  P('ph-product-1',['product'],null,''),
  P('ph-hospitality-8',['hospitality','drone'],null,''),
  P('ph-lifestyle-3',['lifestyle'],null,''),
  P('hideaway-6',['nature','drone'],'hideaway','Haa Alifu Atoll, Maldives'),
  P('ph-interiors-3',['interiors'],null,''),
  P('ph-product-4',['product'],null,''),
];

/* Film: grouped by category; a group with fewer than two films folds into "More films". */
const FILMS = [
  {k:'film-heritance-1', title:'Heritance Aarah', client:'Heritance Hotels & Resorts', loc:'Raa Atoll, Maldives', cat:'Hospitality', project:'heritance'},
  {k:'film-bangkok-2', title:'Four Seasons Bangkok', client:'Four Seasons', loc:'Bangkok, Thailand', cat:'Hospitality', project:'bangkok'},
  {k:'film-hideaway-1', title:'Hideaway Beach Resort & Spa', client:'Hideaway', loc:'Haa Alifu Atoll, Maldives', cat:'Hospitality', project:'hideaway'},
  {k:'film-intercontinental-1', title:'InterContinental', client:'InterContinental', loc:'', cat:'Hospitality', project:'intercontinental'},
  {k:'film-westin-1', title:'The Westin', client:'The Westin', loc:'', cat:'Hospitality', project:'westin'},
  {k:'film-palau-1', title:'Four Seasons Explorer', client:'Four Seasons', loc:'Palau', cat:'Destination', project:'palau'},
  {k:'film-italy-1', title:'Italy', client:'', loc:'Italy', cat:'Destination', project:null},
  {k:'film-italy-4', title:'Italy, coast', client:'', loc:'Italy', cat:'Destination', project:null},
  {k:'film-mazda-1', title:'Mazda', client:'Mazda Europe', loc:'', cat:'Brand & Commercial', project:null},
  {k:'film-garmin-2', title:'Garmin × Mazda', client:'Mazda Europe', loc:'', cat:'Brand & Commercial', project:null},
  {k:'film-dior-1', title:'Dior', client:'Dior', loc:'', cat:'Brand & Commercial', project:null},
];
const HOME_FILMS = [
  {k:'f-01', title:'Film 01', meta:'Client and location to confirm'},
  {k:'f-02', title:'InterContinental', meta:'Film 02', project:'intercontinental'},
  {k:'f-03', title:'InterContinental', meta:'Film 03', project:'intercontinental'},
];

const SERVICES = [
  {id:'photography', name:'Photography', short:'Hospitality, lifestyle, interiors, food and destinations.', img:'s-photography',
   body:'High-end photography for hospitality, lifestyle, architecture, interiors, food and beverage, and destinations. Every shoot is planned around the light, the guest journey and the way the property wants to be seen.',
   deliv:'Retouched image libraries, campaign and editorial imagery, website and OTA sets.'},
  {id:'film', name:'Film', short:'Property films, brand films and short-form stories.', img:'s-film',
   body:'Property films, brand films and short-form stories, from a single hero film to a full series for web and social. Graded to the brand and delivered in every ratio a campaign needs.',
   deliv:'Hero films, cut-downs, vertical edits for social.'},
  {id:'creative-direction', name:'Creative direction', short:'Concept, moodboards, shot planning and on-location direction.', img:'s-creative-direction',
   body:'Concept development, visual direction, moodboards and shot planning, carried through on location. The direction is agreed before we arrive, so time on site goes into production.',
   deliv:'Concept deck, moodboards, shot list, production schedule.'},
  {id:'lifestyle-production', name:'Lifestyle production', short:'Talent, styling and production planning.', img:'s-lifestyle-production',
   body:'Talent, styling, props and production planning for lifestyle scenes that feel natural and on brand.',
   deliv:'Casting, styling, scene planning.'},
  {id:'drone', name:'Drone', short:'Aerial photography and cinematography.', img:'s-drone',
   body:'Aerial photography and cinematography that shows the setting, scale and surroundings of a property. Flights planned in line with local regulations.',
   deliv:'Aerial stills, aerial footage.'},
  {id:'content-libraries', name:'Content libraries', short:'One production, planned for every channel.', img:'s-content-libraries',
   body:'One production, planned to cover every channel. Photography and film delivered as a cohesive library for websites, campaigns, PR, marketing and social media.',
   deliv:''},
];

const LOGOS = [
 ['four-seasons.svg','Four Seasons','palau',58,50],['soneva.png','Soneva',null,40,64],['anantara.png','Anantara',null,44,58],
 ['banyan-tree.svg','Banyan Tree',null,30,64],['six-senses.png','Six Senses','sixsenses',40,62],['heritance-aarah.svg','Heritance','heritance',50,54],
 ['hoiana.png','Hoiana Resort & Golf','hoiana',56,38],['intercontinental.png','InterContinental','intercontinental',54,40],['westin.svg','Westin','westin',50,40],
 ['millenium.png','Millennium Hotels','millennium',60,30],['rixos.svg','Rixos',null,52,40],['lux.svg','LUX* Resorts',null,40,44],
 ['dior.svg','Dior',null,42,28],['mazda.svg','Mazda',null,50,40],['animawings.svg','Animawings',null,52,40]];

const HOME_WORK = ['palau','heritance','sixsenses','hoiana','bangkok','hideaway'];
const HOME_PHOTOS = [
  ['p-1','Hospitality'],['p-2','Interiors'],['p-3','Drone'],['p-4','Lifestyle'],['p-5','Hospitality'],['p-7','Interiors'],['p-8','Food & Beverage']];
